### ISSUE TITLE
When App is Terminated Flutter Callback Events are not working.

### ISSUE THREAD

**Issue by saurav0171** [masashi-sutou/flutter_ios_voip_kit#5]
Whenever app is in terminated state and I hit Voip notification, it successfully hits on my device and shows calling screen. But on accepting call it doesnt hit callback events onDidReceiveIncomingPush and onDidAcceptIncomingCall. Can you please help?

**Comment by masashi-sutou** [comment]
@saurav0171  Thank you for reporting.

`onDidReceiveIncomingPush` is not called when the app is not running, because app is not yet running when `didReceiveIncomingPushWith` is called. This wasn't well explained, so I'll add a comment in the next version.

On the other hand, `onDidAcceptIncomingCall` can be called even if the app is not running.
This is because the app is already running when the incoming call screen is displayed for CallKit.

Please make sure the app is calling `FlutterIOSVoIPKit.instance.onDidAcceptIncomingCall` in the Dart class(ex: main.dart) that is called immediately after the app is launched with VoIP notifications.

**Comment by saurav0171** [comment]
Thanks for your guidance I appreciate it.
Adding to the discussion, I tried calling
FlutterIOSVoIPKit.instance.onDidAcceptIncomingCall
in main.dart. But unfortunately it didn't work.
Steps to reproduce:
1: Voip Notification hits when app is in terminated state.
2: Call picked and it went into app from the beginning and didnt go into
FlutterIOSVoIPKit.instance.onDidAcceptIncomingCall method.

**Comment by saurav0171** [comment]
Moreover, when app is opened via Voip Notification, it runs from very beginning and FlutterIOSVoIPKit.instance.onDidAcceptIncomingCall didn't call.

**Comment by masashi-sutou** [comment]
> Steps to reproduce:
> 1: Voip Notification hits when app is in terminated state.
> 2: Call picked and it went into app from the beginning and didnt go into

Is the incoming call screen of CallKit displayed at 2?
If you see the incoming call screen of CallKit, is your app running after tapped Accept button?

> Can you please let me know the method which is triggered in dart file when the app first opens via Voip Notifications?

There is no such method. This is because when the VoIP notification arrives, the app isn't running yet, so I can't call the Dart code. If your app launches after you accept on the incoming screen I think it will be triggered callbacks in main.dart.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_ios_voip_kit/flutter_ios_voip_kit.dart';

void main() {
  runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final voIPKit = FlutterIOSVoIPKit.instance;

  @override
  void initState() {
    super.initState();
    voIPKit.onDidAcceptIncomingCall = (String channelId, String callerId) {
      // Use local storage(ex: shared_preferences) to save the logs and make sure they are called.
    };

    voIPKit.onDidRejectIncomingCall = (String channelId, String callerId) {
      // Use local storage(ex: shared_preferences) to save the logs and make sure they are called.
    };
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('example'),
      ),
      body: Container(),
    );
  }
}
```

**Comment by Ranjithsp6** [comment]
If **onDidReceiveIncomingPush** is not called when the app is not running then how to get the payload data in this case. Can you let me know guys the possibilities to get the payload

**Comment by PeppeTapick** [comment]
> If **onDidReceiveIncomingPush** is not called when the app is not running then how to get the payload data in this case. Can you let me know guys the possibilities to get the payload

I have the same problem

**Comment by saurav0171** [comment]
You need to get this by making channels and communicating with native ios
files.

**Comment by PeppeTapick** [comment]
Hey man,

Thank you for your reply.
By any chance, do you have some code example on how to do that? I am a bit
weak native side..

**Comment by rekonvald** [comment]
Hi @PeppeTapick, have you found solution? have the same problem(

**Comment by sunilsinghchaudhary00** [comment]
check here i already give a workaround related to this 
[https://stackoverflow.com/questions/78667613/flutter-callkit-incoming-accept-call-not-working-when-app-is-terminated](stackoverflow)
